Fix build with GCC 14 and above
Newer compilers such as GCC 14 ( and above ) have enabled a few compiler
flags by default, -Wincompatible-pointer-types being one of them. Thus
resulting in build errors such as:

frame.c: In function ‘frame_set_numbers_extl’:
frame.c:799:32: error: passing argument 1 of ‘ioncore_grab_establish’ from incompatible pointer type [-Wincompatible-pointer-types]
  799 |         ioncore_grab_establish(frame, numbers_grab_handler, NULL,
      |                                ^~~~~
      |                                |
      |                                WFrame * {aka struct WFrame_struct *}

For now a type casting can be used to supress the error, as change the
type of frame would require touching other parts of the codebase.

First reported on Gentoo Linux with GCC 14, for more details please
reffer https://bugs.gentoo.org/919249

Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>