mod_mgmtmode: add main.o depend on exports.h
Without this change `make --shuffle` (a mode for upcoming GNU make-4.4)
fails the build occasionally as:

    make[1]: Entering directory '/build/notion/mod_mgmtmode'
    gcc -g -Os -W -Wall -pedantic ... -c -o main.o main.c
    main.c:13:10: fatal error: exports.h: No such file or directory
       13 | #include "exports.h"
          |          ^~~~~~~~~~~