mod_notionflux: add mod_notionflux.o depend on exports.h
Without this change `make --shuffle` (a mode for upcoming GNU make-4.4)
fails the build occasionally as:

    make[1]: Entering directory '/build/notion/mod_notionflux'
    gcc -g -Os -W -Wall -pedantic ... -c -o mod_notionflux.o mod_notionflux.c
    mod_notionflux.c:35:10: fatal error: exports.h: No such file or directory
       35 | #include "exports.h"
          |          ^~~~~~~~~~~